<?php
$forbidden['java_properties'] = array(
	"online-mode",
	"server-ip",
	"level-name",
	"query.port",
	"debug",
	"max-players",
	"rcon.port",
	"enable-rcon",
	"rcon.password",
	"enable-query",
	"snooper-enabled",
);

$maxvals['java_properties'] = array(
	"allow-nether"=>array("true","false"),
	"announce-player-achievements" => array("true", "false"),
	"difficulty"=>3,
	"enable-command-block"=>array("true","false"),
	"force-gamemode"=>array("true","false"),
	"gamemode"=>3,
	"generate-structures"=>array("true","false"),
	"generator-settings"=>"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"hardcore"=>array("true","false"),
	"level-seed"=>"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"level-type"=>array("DEFAULT","FLAT","LARGEBIOMES","AMPLIFIED","CUSTOMIZED"),
	"max-build-height"=>256,
	"motd"=>"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"op-permission-level"=>4,
	"player-idle-timeout"=>5*60,
	"pvp"=>array("true","false"),
	"resource-pack"=>"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"server-name"=>"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"spawn-animals"=>array("true","false"),
	"spawn-monsters"=>array("true","false"),
	"spawn-npcs"=>array("true","false"),
	"spawn-protection"=>32,
	"view-distance"=>16,
	"white-list"=>array("true","false"),
);

function java_properties($txtProperties) {
	global $forbidden;
	$result = array();
	
	$lines = explode("\n", $txtProperties);
	$key = "";
	
	$isWaitingOtherLine = false;
	foreach($lines as $i=>$line) {
		if(empty($line) || (!$isWaitingOtherLine && strpos($line,"#") === 0)) continue;
	
		if(!$isWaitingOtherLine) {
			$key = substr($line,0,strpos($line,'='));
			$value = substr($line,strpos($line,'=') + 1, strlen($line));
		}else{
			$value .= $line;
		}

		if(strrpos($value,"\\") === strlen($value)-strlen("\\")) {
			$value = substr($value, 0, strlen($value)-1)."\n";
			$isWaitingOtherLine = true;
		}else{
			$isWaitingOtherLine = false;
		}
	
		if(in_array($key, $forbidden['java_properties']) == TRUE) continue;
	
		$result[$key] = $value;
		unset($lines[$i]);
	}
	ksort($result);
	return $result;
}

function java_properties_write($data){
	global $forbidden, $maxvals;
	
	$content = "# Generated by BGP_Config";
	$content .= "\n";
	$content .= "# ".date("r");
	$content .= "\n";
	$content .= "\n";
	$content .= "# User input";
	$content .= "\n";
	
	foreach($data as $key => $value)
	{
		if(in_array($key, $forbidden['java_properties'])	== TRUE)
			return -1;
		if(isset($maxvals['java_properties'][$key]))
		{
			if(is_array($maxvals['java_properties'][$key]) && !in_array($value, $maxvals['java_properties'][$key]))
				return array(false, ($key." is ".$value." but only allows: ".implode(", ", $maxvals['java_properties'][$key])));
		
			if(is_string($maxvals['java_properties'][$key]) && strlen($value) > strlen($maxvals['java_properties'][$key]))
				return array(false, $key." is too long. (Max: ".strlen($maxvals['java_properties'][$key]).")");
		
			if(is_int($maxvals['java_properties'][$key]) && ($value > $maxvals['java_properties'][$key] || $value < 0))
				return array(false,$key." is too big. (Max: ".$maxvals['java_properties'][$key].")");
		}
		
		$content .= $key . "=".$value."\n";
	}
	return $content;
}

function java_properties_append($server, $box){
	$content = "\n";
	$content .= "# Auto generated content";
	$content .= "\n";
	
	$content .= "level-name=world";
	$content .= "\n";
	$content .= "server-ip=".$box['ip'];
	$content .= "\n";
	$content .= "online-mode=true";
	$content .= "\n";
	$content .= "query.port=".$server['queryport'];
	$content .= "\n";
	$content .= "debug=false";
	$content .= "\n";
	$content .= "max-players=".$server['slots'];
	$content .= "\n";
	$content .= "rcon.port=25575";
	$content .= "\n";
	$content .= "enable-rcon=false";
	$content .= "\n";
	$content .= "enable-query=true";
	$content .= "\n";
	$content .= "rcon.password=";
	$content .= "\n";
	$content .= "snooper-enabled=false";
	
	return $content;
}

function java_properties_reset($server, $box){
	$content = "# Generated by BGP_Config";
	$content .= "\n";
	$content .= "# ".date("r");
	$content .= "\n";
	$content .= "# Auto generated content";
	$content .= "\n";
	
	$content .="allow-nether=true";
	$content .= "\n";
	$content .="announce-player-achievements=true";
	$content .= "\n";
	$content .="difficulty=1";
	$content .= "\n";
	$content .="enable-command-block=false";
	$content .= "\n";
	$content .="force-gamemode=false";
	$content .= "\n";
	$content .="gamemode=0";
	$content .= "\n";
	$content .="generate-structures=true";
	$content .= "\n";
	$content .="generator-settings=";
	$content .= "\n";
	$content .="hardcore=false";
	$content .= "\n";
	$content .="level-seed=";
	$content .= "\n";
	$content .="level-type=DEFAULT";
	$content .= "\n";
	$content .="max-build-height=256";
	$content .= "\n";
	$content .="motd=".$server['name'];
	$content .= "\n";
	$content .="op-permission-level=4";
	$content .= "\n";
	$content .="player-idle-timeout=0";
	$content .= "\n";
	$content .="pvp=true";
	$content .= "\n";
	$content .="resource-pack=";
	$content .= "\n";
	$content .="server-name=".$server['name'];
	$content .= "\n";
	$content .="snooper-enabled=true";
	$content .= "\n";
	$content .="spawn-animals=true";
	$content .= "\n";
	$content .="spawn-monsters=true";
	$content .= "\n";
	$content .="spawn-npcs=true";
	$content .= "\n";
	$content .="spawn-protection=16";
	$content .= "\n";
	$content .="view-distance=16";
	$content .= "\n";
	$content .="white-list=false";
	$content .= "\n";
	$content .= "level-name=world";
	$content .= "\n";
	$content .= "server-ip=".$box['ip'];
	$content .= "\n";
	$content .= "online-mode=true";
	$content .= "\n";
	$content .= "query.port=".$server['queryport'];
	$content .= "\n";
	$content .= "debug=false";
	$content .= "\n";
	$content .= "max-players=".$server['slots'];
	$content .= "\n";
	$content .= "rcon.port=25575";
	$content .= "\n";
	$content .= "enable-rcon=false";
	$content .= "\n";
	$content .= "enable-query=true";
	$content .= "\n";
	$content .= "rcon.password=";
	$content .= "\n";
	$content .= "snooper-enabled=false";
	
	return $content;
}
?>